name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1  
      with:
        persist-credentials: false
    
    - name: Install and Build # 下载依赖 打包项目
      run: |
        yarn
        yarn build
    
    # - name: Install dependencies
    #   run: yarn
    
    # - name: Generate public files
    #   run: yarn build

    - name: Deploy # 将打包内容发布到 github page
        uses: JamesIves/github-pages-deploy-action@3.5.9 # 使用别人写好的 actions
        with:  # 自定义环境变量
          ACCESS_TOKEN: ${{ secrets.DEPLOY_KEY }} # VUE_ADMIN_TEMPLATE 是我的 secret 名称，需要替换成你的
          BRANCH: master
          FOLDER: public
          REPOSITORY_NAME: smpower/smpower.github.io # 这是我的 github page 仓库
          TARGET_FOLDER: / # 打包的文件将放到静态服务器 github-actions-demo 目录下
