name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@hexo
    
    # - name: Install dependencies
    #   run: yarn
    
    # - name: Generate public files
    #   run: yarn build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
        BUILD_SCRIPT: yarn && yarn build